#!/bin/sh
source environ.sh
export KOS_CPP=1
source kos-cc

# This may actually require bash...

# Just supplement the standard C flags and call down.
export KOS_CC="${KOS_CCPLUS}"
export KOS_CFLAGS="${KOS_CFLAGS} ${KOS_CPPFLAGS}"
export KOS_LIBS="-lstdc++ ${KOS_LIBS}"

main "$@"
