# KallistiOS ##version##
#
# examples/gba/Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.2 2002/09/23 23:35:40 bardtx Exp $

all:
	$(MAKE) -C pogo-keen

clean:
	$(MAKE) -C pogo-keen clean
		

