# KallistiOS ##version##
#
# examples/dreamcast/cpp/Makefile
# (c)2001-2002 Dan Potter
#   
# $Id: Makefile,v 1.3 2002/02/24 02:13:07 bardtx Exp $

all:
	$(MAKE) -C gltest
	$(MAKE) -C dcplib
	$(MAKE) -C clock
	$(MAKE) -C modplug_test

clean:
	$(MAKE) -C gltest clean
	$(MAKE) -C dcplib clean
	$(MAKE) -C clock clean
	$(MAKE) -C modplug_test clean
		
dist:
	$(MAKE) -C gltest dist
	$(MAKE) -C dcplib dist
	$(MAKE) -C clock dist
	$(MAKE) -C modplug_test dist


