# KallistiOS ##version##
#
# examples/dreamcast/basic/threading/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.1 2002/04/19 07:53:52 bardtx Exp $

all:
	$(MAKE) -C general

clean:
	$(MAKE) -C general clean
		
dist:
	$(MAKE) -C general dist


