# KallistiOS ##version##
#
# examples/dreamcast/sound/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.2.2.1 2003/06/20 06:31:15 bardtx Exp $

all:
	$(MAKE) -C ghettoplay-vorbis
	$(MAKE) -C hello-ogg
	$(MAKE) -C hello-mp3
	$(MAKE) -C cdda

clean:
	$(MAKE) -C ghettoplay-vorbis clean
	$(MAKE) -C hello-ogg clean
	$(MAKE) -C hello-mp3 clean
	$(MAKE) -C cdda clean
		
dist:
	$(MAKE) -C ghettoplay-vorbis dist
	$(MAKE) -C hello-ogg dist
	$(MAKE) -C hello-mp3 dist
	$(MAKE) -C cdda dist


