# KallistiOS ##version##
#
# examples/dreamcast/lua/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.1 2002/06/13 09:51:16 bardtx Exp $

all:
	$(MAKE) -C basic

clean:
	$(MAKE) -C basic clean
		
dist:
	$(MAKE) -C basic dist


