# KallistiOS ##version##
#
# examples/dreamcast/tsunami/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.1.2.1 2003/06/20 06:10:25 bardtx Exp $

all:
	$(MAKE) -C font
	$(MAKE) -C banner
	$(MAKE) -C genmenu

clean:
	$(MAKE) -C font clean
	$(MAKE) -C banner clean
	$(MAKE) -C genmenu clean
		
dist:
	$(MAKE) -C font dist
	$(MAKE) -C banner dist
	$(MAKE) -C genmenu dist


